[package]
name = "twist_test"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.32"
lambda-twist = "0.7"
cv-core = "0.6"
cv = "0.6"
rand = { version = "0.7.3", features = ["small_rng"] }
arrsac = "0.11.0"
